// @generated by tools/generate_ipc.py from schemas/ipc/control-plane.json.
// Do not edit this file directly.

pub const PROTOCOL_VERSION: u16 = 1;
pub const MAX_REGISTERED_PROCESSES: usize = 1024;

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum Capability {
    KernelControlChannel = 0,
    ProfileRegistry = 1,
    ProcessBroker = 2,
    NavigationCommit = 3,
    PermissionPolicy = 4,
    AgentPolicy = 5,
    SessionJournal = 6,
    UiCommands = 7,
    NetworkRequestBroker = 8,
    StorageRequestBroker = 9,
    DecoderRoute = 10,
    RequestNavigation = 11,
    SubmitGpuWork = 12,
    EmitDiagnostics = 13,
    AssignedIpc = 14,
    AssignedSharedMemory = 15,
    AssignedSurface = 16,
    ReadOnlyFontHandles = 17,
    NetworkSockets = 18,
    ProxyResolution = 19,
    CertificateVerificationAdapter = 20,
    HttpCache = 21,
    CookieAttachment = 22,
    ProfileStorageRoots = 23,
    QuotaDatabase = 24,
    LogicalOriginStores = 25,
    GraphicsDevice = 26,
    AssignedSurfaces = 27,
    ValidatedSharedMemory = 28,
    TaskScopedInput = 29,
    BoundedOutput = 30,
    OptionalAssignedDeviceHandle = 31,
    DeclaredExtensionApis = 32,
    GrantedHosts = 33,
    ExtensionStorage = 34,
    AttachedTargetProtocol = 35,
    LocalFrontendResources = 36,
    GrantedObservations = 37,
    ModelAdapter = 38,
    ProposedActions = 39,
    AuditAppend = 40,
    UpdateEndpoint = 41,
    SignedMetadata = 42,
    StagingDirectory = 43,
    VersionInstallRoots = 44,
    CrashChannels = 45,
    BoundedDumpDirectory = 46,
    BuildIdSymbols = 47,
}

impl Capability {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::KernelControlChannel => "kernel_control_channel",
            Self::ProfileRegistry => "profile_registry",
            Self::ProcessBroker => "process_broker",
            Self::NavigationCommit => "navigation_commit",
            Self::PermissionPolicy => "permission_policy",
            Self::AgentPolicy => "agent_policy",
            Self::SessionJournal => "session_journal",
            Self::UiCommands => "ui_commands",
            Self::NetworkRequestBroker => "network_request_broker",
            Self::StorageRequestBroker => "storage_request_broker",
            Self::DecoderRoute => "decoder_route",
            Self::RequestNavigation => "request_navigation",
            Self::SubmitGpuWork => "submit_gpu_work",
            Self::EmitDiagnostics => "emit_diagnostics",
            Self::AssignedIpc => "assigned_ipc",
            Self::AssignedSharedMemory => "assigned_shared_memory",
            Self::AssignedSurface => "assigned_surface",
            Self::ReadOnlyFontHandles => "read_only_font_handles",
            Self::NetworkSockets => "network_sockets",
            Self::ProxyResolution => "proxy_resolution",
            Self::CertificateVerificationAdapter => "certificate_verification_adapter",
            Self::HttpCache => "http_cache",
            Self::CookieAttachment => "cookie_attachment",
            Self::ProfileStorageRoots => "profile_storage_roots",
            Self::QuotaDatabase => "quota_database",
            Self::LogicalOriginStores => "logical_origin_stores",
            Self::GraphicsDevice => "graphics_device",
            Self::AssignedSurfaces => "assigned_surfaces",
            Self::ValidatedSharedMemory => "validated_shared_memory",
            Self::TaskScopedInput => "task_scoped_input",
            Self::BoundedOutput => "bounded_output",
            Self::OptionalAssignedDeviceHandle => "optional_assigned_device_handle",
            Self::DeclaredExtensionApis => "declared_extension_apis",
            Self::GrantedHosts => "granted_hosts",
            Self::ExtensionStorage => "extension_storage",
            Self::AttachedTargetProtocol => "attached_target_protocol",
            Self::LocalFrontendResources => "local_frontend_resources",
            Self::GrantedObservations => "granted_observations",
            Self::ModelAdapter => "model_adapter",
            Self::ProposedActions => "proposed_actions",
            Self::AuditAppend => "audit_append",
            Self::UpdateEndpoint => "update_endpoint",
            Self::SignedMetadata => "signed_metadata",
            Self::StagingDirectory => "staging_directory",
            Self::VersionInstallRoots => "version_install_roots",
            Self::CrashChannels => "crash_channels",
            Self::BoundedDumpDirectory => "bounded_dump_directory",
            Self::BuildIdSymbols => "build_id_symbols",
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum ProcessRole {
    BrowserKernel = 1,
    Renderer = 2,
    Network = 3,
    Storage = 4,
    Gpu = 5,
    MediaUtility = 6,
    ExtensionHost = 7,
    Devtools = 8,
    AgentHost = 9,
    Updater = 10,
    CrashHandler = 11,
}

impl ProcessRole {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::BrowserKernel => "browser_kernel",
            Self::Renderer => "renderer",
            Self::Network => "network",
            Self::Storage => "storage",
            Self::Gpu => "gpu",
            Self::MediaUtility => "media_utility",
            Self::ExtensionHost => "extension_host",
            Self::Devtools => "devtools",
            Self::AgentHost => "agent_host",
            Self::Updater => "updater",
            Self::CrashHandler => "crash_handler",
        }
    }

    #[must_use]
    pub const fn default_capability_bits(self) -> u128 {
        match self {
            Self::BrowserKernel => 10239_u128,
            Self::Renderer => 260097_u128,
            Self::Network => 8134657_u128,
            Self::Storage => 58728449_u128,
            Self::Gpu => 469770241_u128,
            Self::MediaUtility => 3758104577_u128,
            Self::ExtensionHost => 30064779265_u128,
            Self::Devtools => 103079223297_u128,
            Self::AgentHost => 2061584310273_u128,
            Self::Updater => 32985348841473_u128,
            Self::CrashHandler => 246290604630017_u128,
        }
    }

    #[must_use]
    pub const fn may_launch(self, child: Self) -> bool {
        matches!(
            (self, child),
            (Self::BrowserKernel, Self::Renderer)
                | (Self::BrowserKernel, Self::Network)
                | (Self::BrowserKernel, Self::Storage)
                | (Self::BrowserKernel, Self::Gpu)
                | (Self::BrowserKernel, Self::MediaUtility)
                | (Self::BrowserKernel, Self::ExtensionHost)
                | (Self::BrowserKernel, Self::Devtools)
                | (Self::BrowserKernel, Self::AgentHost)
                | (Self::BrowserKernel, Self::Updater)
                | (Self::BrowserKernel, Self::CrashHandler)
        )
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, PartialEq)]
pub enum DocumentScope {
    Required,
    Optional,
    Forbidden,
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u8)]
pub enum QueueClass {
    Urgent = 1,
    Control = 2,
}

impl QueueClass {
    #[must_use]
    pub const fn maximum_items(self) -> usize {
        match self {
            Self::Urgent => 64,
            Self::Control => 256,
        }
    }

    #[must_use]
    pub const fn maximum_queued_bytes(self) -> usize {
        match self {
            Self::Urgent => 262144,
            Self::Control => 1048576,
        }
    }
}

#[derive(Clone, Copy, Debug, Eq, Hash, Ord, PartialEq, PartialOrd)]
#[repr(u16)]
pub enum MessageKind {
    ProcessHello = 1,
    ProcessReady = 2,
    Shutdown = 3,
    NavigationIntent = 10,
    NavigationCommit = 11,
    NetworkRequest = 20,
    NetworkResponse = 21,
    StorageRequest = 30,
    StorageResponse = 31,
    GpuSubmit = 40,
    DecodeRequest = 50,
    DiagnosticEvent = 60,
    AgentActionProposal = 70,
    ExtensionApiRequest = 80,
}

impl MessageKind {
    #[must_use]
    pub const fn as_str(self) -> &'static str {
        match self {
            Self::ProcessHello => "process_hello",
            Self::ProcessReady => "process_ready",
            Self::Shutdown => "shutdown",
            Self::NavigationIntent => "navigation_intent",
            Self::NavigationCommit => "navigation_commit",
            Self::NetworkRequest => "network_request",
            Self::NetworkResponse => "network_response",
            Self::StorageRequest => "storage_request",
            Self::StorageResponse => "storage_response",
            Self::GpuSubmit => "gpu_submit",
            Self::DecodeRequest => "decode_request",
            Self::DiagnosticEvent => "diagnostic_event",
            Self::AgentActionProposal => "agent_action_proposal",
            Self::ExtensionApiRequest => "extension_api_request",
        }
    }

    #[must_use]
    pub const fn maximum_encoded_bytes(self) -> usize {
        match self {
            Self::ProcessHello => 4096,
            Self::ProcessReady => 4096,
            Self::Shutdown => 4096,
            Self::NavigationIntent => 8192,
            Self::NavigationCommit => 16384,
            Self::NetworkRequest => 32768,
            Self::NetworkResponse => 65536,
            Self::StorageRequest => 32768,
            Self::StorageResponse => 65536,
            Self::GpuSubmit => 65536,
            Self::DecodeRequest => 32768,
            Self::DiagnosticEvent => 16384,
            Self::AgentActionProposal => 32768,
            Self::ExtensionApiRequest => 32768,
        }
    }

    #[must_use]
    pub const fn document_scope(self) -> DocumentScope {
        match self {
            Self::ProcessHello => DocumentScope::Forbidden,
            Self::ProcessReady => DocumentScope::Forbidden,
            Self::Shutdown => DocumentScope::Forbidden,
            Self::NavigationIntent => DocumentScope::Required,
            Self::NavigationCommit => DocumentScope::Required,
            Self::NetworkRequest => DocumentScope::Required,
            Self::NetworkResponse => DocumentScope::Required,
            Self::StorageRequest => DocumentScope::Required,
            Self::StorageResponse => DocumentScope::Required,
            Self::GpuSubmit => DocumentScope::Required,
            Self::DecodeRequest => DocumentScope::Optional,
            Self::DiagnosticEvent => DocumentScope::Optional,
            Self::AgentActionProposal => DocumentScope::Required,
            Self::ExtensionApiRequest => DocumentScope::Optional,
        }
    }

    #[must_use]
    pub const fn required_capability(self) -> Option<Capability> {
        match self {
            Self::ProcessHello => Some(Capability::KernelControlChannel),
            Self::ProcessReady => Some(Capability::KernelControlChannel),
            Self::Shutdown => Some(Capability::ProcessBroker),
            Self::NavigationIntent => Some(Capability::RequestNavigation),
            Self::NavigationCommit => Some(Capability::NavigationCommit),
            Self::NetworkRequest => Some(Capability::NetworkRequestBroker),
            Self::NetworkResponse => Some(Capability::NetworkSockets),
            Self::StorageRequest => Some(Capability::StorageRequestBroker),
            Self::StorageResponse => Some(Capability::ProfileStorageRoots),
            Self::GpuSubmit => Some(Capability::SubmitGpuWork),
            Self::DecodeRequest => Some(Capability::DecoderRoute),
            Self::DiagnosticEvent => Some(Capability::EmitDiagnostics),
            Self::AgentActionProposal => Some(Capability::ProposedActions),
            Self::ExtensionApiRequest => Some(Capability::DeclaredExtensionApis),
        }
    }

    #[must_use]
    pub const fn allows_route(self, sender: ProcessRole, receiver: ProcessRole) -> bool {
        match self {
            Self::ProcessHello => matches!(
                (sender, receiver),
                (ProcessRole::Renderer, ProcessRole::BrowserKernel)
                    | (ProcessRole::Network, ProcessRole::BrowserKernel)
                    | (ProcessRole::Storage, ProcessRole::BrowserKernel)
                    | (ProcessRole::Gpu, ProcessRole::BrowserKernel)
                    | (ProcessRole::MediaUtility, ProcessRole::BrowserKernel)
                    | (ProcessRole::ExtensionHost, ProcessRole::BrowserKernel)
                    | (ProcessRole::Devtools, ProcessRole::BrowserKernel)
                    | (ProcessRole::AgentHost, ProcessRole::BrowserKernel)
                    | (ProcessRole::Updater, ProcessRole::BrowserKernel)
                    | (ProcessRole::CrashHandler, ProcessRole::BrowserKernel)
            ),
            Self::ProcessReady => matches!(
                (sender, receiver),
                (ProcessRole::Renderer, ProcessRole::BrowserKernel)
                    | (ProcessRole::Network, ProcessRole::BrowserKernel)
                    | (ProcessRole::Storage, ProcessRole::BrowserKernel)
                    | (ProcessRole::Gpu, ProcessRole::BrowserKernel)
                    | (ProcessRole::MediaUtility, ProcessRole::BrowserKernel)
                    | (ProcessRole::ExtensionHost, ProcessRole::BrowserKernel)
                    | (ProcessRole::Devtools, ProcessRole::BrowserKernel)
                    | (ProcessRole::AgentHost, ProcessRole::BrowserKernel)
                    | (ProcessRole::Updater, ProcessRole::BrowserKernel)
                    | (ProcessRole::CrashHandler, ProcessRole::BrowserKernel)
            ),
            Self::Shutdown => matches!(
                (sender, receiver),
                (ProcessRole::BrowserKernel, ProcessRole::Renderer)
                    | (ProcessRole::BrowserKernel, ProcessRole::Network)
                    | (ProcessRole::BrowserKernel, ProcessRole::Storage)
                    | (ProcessRole::BrowserKernel, ProcessRole::Gpu)
                    | (ProcessRole::BrowserKernel, ProcessRole::MediaUtility)
                    | (ProcessRole::BrowserKernel, ProcessRole::ExtensionHost)
                    | (ProcessRole::BrowserKernel, ProcessRole::Devtools)
                    | (ProcessRole::BrowserKernel, ProcessRole::AgentHost)
                    | (ProcessRole::BrowserKernel, ProcessRole::Updater)
                    | (ProcessRole::BrowserKernel, ProcessRole::CrashHandler)
            ),
            Self::NavigationIntent => matches!(
                (sender, receiver),
                (ProcessRole::Renderer, ProcessRole::BrowserKernel)
            ),
            Self::NavigationCommit => matches!(
                (sender, receiver),
                (ProcessRole::BrowserKernel, ProcessRole::Renderer)
            ),
            Self::NetworkRequest => matches!(
                (sender, receiver),
                (ProcessRole::BrowserKernel, ProcessRole::Network)
            ),
            Self::NetworkResponse => matches!(
                (sender, receiver),
                (ProcessRole::Network, ProcessRole::BrowserKernel)
            ),
            Self::StorageRequest => matches!(
                (sender, receiver),
                (ProcessRole::BrowserKernel, ProcessRole::Storage)
            ),
            Self::StorageResponse => matches!(
                (sender, receiver),
                (ProcessRole::Storage, ProcessRole::BrowserKernel)
            ),
            Self::GpuSubmit => matches!(
                (sender, receiver),
                (ProcessRole::Renderer, ProcessRole::Gpu)
            ),
            Self::DecodeRequest => matches!(
                (sender, receiver),
                (ProcessRole::BrowserKernel, ProcessRole::MediaUtility)
            ),
            Self::DiagnosticEvent => matches!(
                (sender, receiver),
                (ProcessRole::Renderer, ProcessRole::BrowserKernel)
                    | (ProcessRole::Network, ProcessRole::BrowserKernel)
                    | (ProcessRole::Storage, ProcessRole::BrowserKernel)
                    | (ProcessRole::Gpu, ProcessRole::BrowserKernel)
                    | (ProcessRole::MediaUtility, ProcessRole::BrowserKernel)
                    | (ProcessRole::ExtensionHost, ProcessRole::BrowserKernel)
                    | (ProcessRole::Devtools, ProcessRole::BrowserKernel)
                    | (ProcessRole::AgentHost, ProcessRole::BrowserKernel)
                    | (ProcessRole::Updater, ProcessRole::BrowserKernel)
                    | (ProcessRole::CrashHandler, ProcessRole::BrowserKernel)
            ),
            Self::AgentActionProposal => matches!(
                (sender, receiver),
                (ProcessRole::AgentHost, ProcessRole::BrowserKernel)
            ),
            Self::ExtensionApiRequest => matches!(
                (sender, receiver),
                (ProcessRole::ExtensionHost, ProcessRole::BrowserKernel)
            ),
        }
    }
}
